Updated mainGame.cs
issue: ERROR!
/tmp/UOIVmlH4tl/Main.cs(183,33): error CS0103: The name 'Terrains' does not exist in the current context

=== Code Exited With Errors ===